# Generated by Django 5.2.5 on 2025-11-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='objetos/imagenes/'),
        ),
    ]
