# Generated by Django 5.2.5 on 2025-11-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_objeto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='gramos',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
