# Generated by Django 5.2.5 on 2025-11-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_objeto_gramos'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='puntaje',
            field=models.FloatField(default=0),
        ),
    ]
